//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Il2Native.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Il2Native.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare i8* @malloc(i32) #99900
        ///
        ///; Function Attrs: nounwind
        ///;declare void @llvm.memcpy.p0i8.p0i8.i32(i8* nocapture, i8* nocapture readonly, i32, i32, i1) #88801
        ///declare void @llvm.memcpy.p0i8.p0i8.i32(i8* nocapture, i8* nocapture, i32, i32, i1) #88801
        ///declare void @llvm.memset.p0i8.i32(i8*, i8, i32, i32, i1) #88802
        ///
        ///declare { i8, i1 } @llvm.sadd.with.overflow.i8(i8, i8) #0
        ///declare { i16, i1 } @llvm.sadd.with.overflow.i16(i16, i16) #0
        ///declare { i32, i1 } @llvm.sadd.with.overflow.i32(i32, i32) #0
        ///de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string llvm_declarations {
            get {
                return ResourceManager.GetString("llvm_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare void @GC_init() #0
        ///declare i8* @GC_malloc(i32) #0
        ///declare i8* @GC_malloc_atomic(i32) #0
        ///declare i8* @GC_realloc(i8*, i32) #0
        ///declare i32 @GC_get_heap_size() #0
        ///.
        /// </summary>
        internal static string llvm_gc_declarations {
            get {
                return ResourceManager.GetString("llvm_gc_declarations", resourceCulture);
            }
        }
    }
}
