//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Il2Native.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Il2Native.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template &lt;typename T&gt; class __array_t : public &lt;&lt;%assemblyName%&gt;&gt;::System::Array
        ///{
        ///};.
        /// </summary>
        internal static string c_declarations {
            get {
                return ResourceManager.GetString("c_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string c_definitions {
            get {
                return ResourceManager.GetString("c_definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;cstdint&gt;
        ///
        ///template &lt;typename T&gt; class __array_t;.
        /// </summary>
        internal static string c_forward_declarations {
            get {
                return ResourceManager.GetString("c_forward_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Decimals
        ///extern &quot;C&quot; Double pow(Double value, Double power);
        ///extern &quot;C&quot; Double fabs(Double value);
        ///
        ///typedef union {
        ///	UInt64 int64;
        ///	struct {
        ///#if BIGENDIAN
        ///		UInt32 Hi;
        ///		UInt32 Lo;
        ///#else            
        ///		UInt32 Lo;
        ///		UInt32 Hi;
        ///#endif           
        ///	} u;
        ///} SPLIT64__;
        ///
        ///typedef union{
        ///	struct {
        ///#if BIGENDIAN
        ///		UInt32 sign : 1;
        ///		UInt32 exp : 11;
        ///		UInt32 mantHi : 20;
        ///		UInt32 mantLo;
        ///#else // BIGENDIAN
        ///		UInt32 mantLo;
        ///		UInt32 mantHi : 20;
        ///		UInt32 exp : 11;
        ///		UInt32 sign : 1;
        ///#endif [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string decimals {
            get {
                return ResourceManager.GetString("decimals", resourceCulture);
            }
        }
    }
}
