//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Il2Native.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Il2Native.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifdef _MSC_VER
        ///typedef __int8 int8_t;
        ///typedef __int16 int16_t;
        ///typedef __int32 int32_t;
        ///typedef __int64 int64_t;
        ///typedef unsigned __int8 uint8_t;
        ///typedef unsigned __int16 uint16_t;
        ///typedef unsigned __int32 uint32_t;
        ///typedef unsigned __int64 uint64_t;
        ///
        ///extern &quot;C&quot; void* alloca(uint32_t);
        ///
        ///extern &quot;C&quot; void* memcpy(void* dst, void* src, int32_t size);
        ///extern &quot;C&quot; void* memset(void *,int32_t,uint32_t);
        ///
        ///template&lt;typename T&gt; T compare_and_swap(T* reg, T oldval, T newval)
        ///{
        ///	T old_reg_val = *reg;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string c_declarations {
            get {
                return ResourceManager.GetString("c_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extern &quot;C&quot; void GC_init();
        ///extern &quot;C&quot; void* GC_malloc(UInt32);
        ///
        ///#undef GC_MALLOC
        ///#define GC_MALLOC GC_malloc
        ///
        ///#undef GC_INIT
        ///#define GC_INIT GC_init.
        /// </summary>
        internal static string gc_declarations {
            get {
                return ResourceManager.GetString("gc_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #define GC_DEBUG
        ///#include &quot;gc.h&quot;.
        /// </summary>
        internal static string gc_declarations_debug {
            get {
                return ResourceManager.GetString("gc_declarations_debug", resourceCulture);
            }
        }
    }
}
